HEADERS += \
    $$PWD/include/MultiFramedRTPSink.hh \
    $$PWD/include/AVIDemuxedServerMediaSubsession.hh \
    $$PWD/include/RTSPClient.hh \
    $$PWD/include/AVIDemux.hh \
    $$PWD/EBMLNumber.hh \
    $$PWD/H263plusVideoStreamParser.hh \
    $$PWD/MatroskaDemuxedTrack.hh \
    $$PWD/MatroskaFileServerMediaSubsession.hh \
    $$PWD/MP3AudioMatroskaFileServerMediaSubsession.hh \
    $$PWD/MP3StreamState.hh \
    $$PWD/MPEGVideoStreamParser.hh \
    $$PWD/OggFileParser.hh \
    $$PWD/include/AACAudioStreamFramer.hh \
    $$PWD/include/AC3AudioFileServerMediaSubsession.hh \
    $$PWD/include/AC3AudioRTPSink.hh \
    $$PWD/include/AC3AudioRTPSource.hh \
    $$PWD/include/AC3AudioStreamFramer.hh \
    $$PWD/include/ADTSAudioFileServerMediaSubsession.hh \
    $$PWD/include/ADTSAudioFileSource.hh \
    $$PWD/include/AMRAudioFileServerMediaSubsession.hh \
    $$PWD/include/AMRAudioFileSink.hh \
    $$PWD/include/AMRAudioFileSource.hh \
    $$PWD/include/AMRAudioRTPSink.hh \
    $$PWD/include/AMRAudioRTPSource.hh \
    $$PWD/include/AMRAudioSource.hh \
    $$PWD/include/AudioInputDevice.hh \
    $$PWD/include/AudioRTPSink.hh \
    $$PWD/include/AVIDemuxedElementaryStream.hh \
    $$PWD/include/AVIFileServerDemux.hh \
    $$PWD/include/AVIFileSink.hh \
    $$PWD/include/AVIVideoDiscreteFramer.hh \
    $$PWD/include/Base64.hh \
    $$PWD/include/BasicUDPSink.hh \
    $$PWD/include/BasicUDPSource.hh \
    $$PWD/include/BitVector.hh \
    $$PWD/include/ByteStreamFileSource.hh \
    $$PWD/include/ByteStreamMemoryBufferSource.hh \
    $$PWD/include/ByteStreamMultiFileSource.hh \
    $$PWD/include/DeviceSource.hh \
    $$PWD/include/DigestAuthentication.hh \
    $$PWD/include/DVVideoFileServerMediaSubsession.hh \
    $$PWD/include/DVVideoRTPSink.hh \
    $$PWD/include/DVVideoRTPSource.hh \
    $$PWD/include/DVVideoStreamFramer.hh \
    $$PWD/include/FileServerMediaSubsession.hh \
    $$PWD/include/FileSink.hh \
    $$PWD/include/FramedFileSource.hh \
    $$PWD/include/FramedFilter.hh \
    $$PWD/include/FramedSource.hh \
    $$PWD/include/GenericMediaServer.hh \
    $$PWD/include/GSMAudioRTPSink.hh \
    $$PWD/include/H261VideoRTPSource.hh \
    $$PWD/include/H263plusVideoFileServerMediaSubsession.hh \
    $$PWD/include/H263plusVideoRTPSink.hh \
    $$PWD/include/H263plusVideoRTPSource.hh \
    $$PWD/include/H263plusVideoStreamFramer.hh \
    $$PWD/include/H264or5VideoFileSink.hh \
    $$PWD/include/H264or5VideoRTPSink.hh \
    $$PWD/include/H264or5VideoStreamDiscreteFramer.hh \
    $$PWD/include/H264or5VideoStreamFramer.hh \
    $$PWD/include/H264VideoFileServerMediaSubsession.hh \
    $$PWD/include/H264VideoFileSink.hh \
    $$PWD/include/H264VideoRTPSink.hh \
    $$PWD/include/H264VideoRTPSource.hh \
    $$PWD/include/H264VideoStreamDiscreteFramer.hh \
    $$PWD/include/H264VideoStreamFramer.hh \
    $$PWD/include/H265VideoFileServerMediaSubsession.hh \
    $$PWD/include/H265VideoFileSink.hh \
    $$PWD/include/H265VideoRTPSink.hh \
    $$PWD/include/H265VideoRTPSource.hh \
    $$PWD/include/H265VideoStreamDiscreteFramer.hh \
    $$PWD/include/H265VideoStreamFramer.hh \
    $$PWD/include/InputFile.hh \
    $$PWD/include/JPEGVideoRTPSink.hh \
    $$PWD/include/JPEGVideoRTPSource.hh \
    $$PWD/include/JPEGVideoSource.hh \
    $$PWD/include/liveMedia.hh \
    $$PWD/include/liveMedia_version.hh \
    $$PWD/include/Locale.hh \
    $$PWD/include/MatroskaFile.hh \
    $$PWD/MatroskaFileParser.hh \
    $$PWD/include/MatroskaFileServerDemux.hh \
    $$PWD/include/Media.hh \
    $$PWD/include/MediaSession.hh \
    $$PWD/include/MediaSink.hh \
    $$PWD/include/MediaSource.hh \
    $$PWD/include/MediaTranscodingTable.hh \
    $$PWD/include/MP3ADU.hh \
    $$PWD/MP3ADUdescriptor.hh \
    $$PWD/include/MP3ADUinterleaving.hh \
    $$PWD/include/MP3ADURTPSink.hh \
    $$PWD/include/MP3ADURTPSource.hh \
    $$PWD/include/MP3ADUTranscoder.hh \
    $$PWD/include/MP3AudioFileServerMediaSubsession.hh \
    $$PWD/include/MP3FileSource.hh \
    $$PWD/MP3Internals.hh \
    $$PWD/MP3InternalsHuffman.hh \
    $$PWD/include/MP3Transcoder.hh \
    $$PWD/include/MPEG1or2AudioRTPSink.hh \
    $$PWD/include/MPEG1or2AudioRTPSource.hh \
    $$PWD/include/MPEG1or2AudioStreamFramer.hh \
    $$PWD/include/MPEG1or2Demux.hh \
    $$PWD/include/MPEG1or2DemuxedElementaryStream.hh \
    $$PWD/include/MPEG1or2DemuxedServerMediaSubsession.hh \
    $$PWD/include/MPEG1or2FileServerDemux.hh \
    $$PWD/include/MPEG1or2VideoFileServerMediaSubsession.hh \
    $$PWD/include/MPEG1or2VideoRTPSink.hh \
    $$PWD/include/MPEG1or2VideoRTPSource.hh \
    $$PWD/include/MPEG1or2VideoStreamDiscreteFramer.hh \
    $$PWD/include/MPEG1or2VideoStreamFramer.hh \
    $$PWD/include/MPEG2IndexFromTransportStream.hh \
    $$PWD/include/MPEG2TransportFileServerMediaSubsession.hh \
    $$PWD/include/MPEG2TransportStreamAccumulator.hh \
    $$PWD/include/MPEG2TransportStreamFramer.hh \
    $$PWD/include/MPEG2TransportStreamFromESSource.hh \
    $$PWD/include/MPEG2TransportStreamFromPESSource.hh \
    $$PWD/include/MPEG2TransportStreamIndexFile.hh \
    $$PWD/include/MPEG2TransportStreamMultiplexor.hh \
    $$PWD/include/MPEG2TransportStreamTrickModeFilter.hh \
    $$PWD/include/MPEG2TransportUDPServerMediaSubsession.hh \
    $$PWD/include/MPEG4ESVideoRTPSink.hh \
    $$PWD/include/MPEG4ESVideoRTPSource.hh \
    $$PWD/include/MPEG4GenericRTPSink.hh \
    $$PWD/include/MPEG4GenericRTPSource.hh \
    $$PWD/include/MPEG4LATMAudioRTPSink.hh \
    $$PWD/include/MPEG4LATMAudioRTPSource.hh \
    $$PWD/include/MPEG4VideoFileServerMediaSubsession.hh \
    $$PWD/include/MPEG4VideoStreamDiscreteFramer.hh \
    $$PWD/include/MPEG4VideoStreamFramer.hh \
    $$PWD/include/MPEGVideoStreamFramer.hh \
    $$PWD/include/MultiFramedRTPSource.hh \
    $$PWD/OggDemuxedTrack.hh \
    $$PWD/include/OggFile.hh \
    $$PWD/include/OggFileServerDemux.hh \
    $$PWD/OggFileServerMediaSubsession.hh \
    $$PWD/include/OggFileSink.hh \
    $$PWD/include/OnDemandServerMediaSubsession.hh \
    $$PWD/include/ourMD5.hh \
    $$PWD/include/OutputFile.hh \
    $$PWD/include/PassiveServerMediaSubsession.hh \
    $$PWD/include/ProxyServerMediaSession.hh \
    $$PWD/include/QCELPAudioRTPSource.hh \
    $$PWD/include/QuickTimeFileSink.hh \
    $$PWD/include/QuickTimeGenericRTPSource.hh \
    $$PWD/include/RTCP.hh \
    $$PWD/rtcp_from_spec.h \
    $$PWD/include/RTPInterface.hh \
    $$PWD/include/RTPSink.hh \
    $$PWD/include/RTPSource.hh \
    $$PWD/include/RTSPCommon.hh \
    $$PWD/include/RTSPRegisterSender.hh \
    $$PWD/include/RTSPServer.hh \
    $$PWD/include/RTSPServerSupportingHTTPStreaming.hh \
    $$PWD/include/ServerMediaSession.hh \
    $$PWD/include/SimpleRTPSink.hh \
    $$PWD/include/SimpleRTPSource.hh \
    $$PWD/include/SIPClient.hh \
    $$PWD/StreamParser.hh \
    $$PWD/include/StreamReplicator.hh \
    $$PWD/include/T140TextRTPSink.hh \
    $$PWD/include/TCPStreamSink.hh \
    $$PWD/include/TextRTPSink.hh \
    $$PWD/include/TheoraVideoRTPSink.hh \
    $$PWD/include/TheoraVideoRTPSource.hh \
    $$PWD/include/uLawAudioFilter.hh \
    $$PWD/include/VideoRTPSink.hh \
    $$PWD/include/VorbisAudioRTPSink.hh \
    $$PWD/include/VorbisAudioRTPSource.hh \
    $$PWD/include/VP8VideoRTPSink.hh \
    $$PWD/include/VP8VideoRTPSource.hh \
    $$PWD/include/VP9VideoRTPSink.hh \
    $$PWD/include/VP9VideoRTPSource.hh \
    $$PWD/include/WAVAudioFileServerMediaSubsession.hh \
    $$PWD/include/WAVAudioFileSource.hh

SOURCES += \
    $$PWD/MultiFramedRTPSink.cpp \
    $$PWD/RTSPServer.cpp \
    $$PWD/RTSPCommon.cpp \
    $$PWD/MediaSession.cpp \
    $$PWD/ServerMediaSession.cpp \
    $$PWD/AVIDemuxedServerMediaSubsession.cpp \
    $$PWD/OnDemandServerMediaSubsession.cpp \
    $$PWD/AVIDemux.cpp \
    $$PWD/AVIFileServerDemux.cpp \
    $$PWD/GenericMediaServer.cpp \
    $$PWD/RTSPClient.cpp \
    $$PWD/MediaSink.cpp \
    $$PWD/AC3AudioStreamFramer.cpp \
    $$PWD/AMRAudioFileSource.cpp \
    $$PWD/AMRAudioRTPSink.cpp \
    $$PWD/AudioInputDevice.cpp \
    $$PWD/AVIFileSink.cpp \
    $$PWD/Base64.cpp \
    $$PWD/ByteStreamMemoryBufferSource.cpp \
    $$PWD/DVVideoFileServerMediaSubsession.cpp \
    $$PWD/DVVideoRTPSink.cpp \
    $$PWD/FileServerMediaSubsession.cpp \
    $$PWD/GSMAudioRTPSink.cpp \
    $$PWD/H263plusVideoStreamParser.cpp \
    $$PWD/H264or5VideoFileSink.cpp \
    $$PWD/H264or5VideoStreamDiscreteFramer.cpp \
    $$PWD/H264VideoRTPSink.cpp \
    $$PWD/H264VideoStreamDiscreteFramer.cpp \
    $$PWD/H265VideoRTPSink.cpp \
    $$PWD/H265VideoStreamDiscreteFramer.cpp \
    $$PWD/H265VideoStreamFramer.cpp \
    $$PWD/InputFile.cpp \
    $$PWD/Locale.cpp \
    $$PWD/MP3ADUdescriptor.cpp \
    $$PWD/MP3ADUinterleaving.cpp \
    $$PWD/MP3ADUTranscoder.cpp \
    $$PWD/MP3AudioFileServerMediaSubsession.cpp \
    $$PWD/MP3InternalsHuffman.cpp \
    $$PWD/MP3InternalsHuffmanTable.cpp \
    $$PWD/MPEG1or2AudioRTPSink.cpp \
    $$PWD/MPEG1or2AudioRTPSource.cpp \
    $$PWD/MPEG1or2Demux.cpp \
    $$PWD/MPEG1or2DemuxedElementaryStream.cpp \
    $$PWD/MPEG1or2FileServerDemux.cpp \
    $$PWD/MPEG1or2VideoFileServerMediaSubsession.cpp \
    $$PWD/MPEG1or2VideoRTPSource.cpp \
    $$PWD/MPEG1or2VideoStreamDiscreteFramer.cpp \
    $$PWD/MPEG2TransportFileServerMediaSubsession.cpp \
    $$PWD/MPEG2TransportStreamAccumulator.cpp \
    $$PWD/MPEG2TransportStreamFramer.cpp \
    $$PWD/MPEG2TransportStreamIndexFile.cpp \
    $$PWD/MPEG2TransportStreamMultiplexor.cpp \
    $$PWD/MPEG4GenericRTPSource.cpp \
    $$PWD/MPEG4LATMAudioRTPSink.cpp \
    $$PWD/MPEG4LATMAudioRTPSource.cpp \
    $$PWD/MPEG4VideoStreamFramer.cpp \
    $$PWD/MPEGVideoStreamParser.cpp \
    $$PWD/OggFileServerDemux.cpp \
    $$PWD/OggFileServerMediaSubsession.cpp \
    $$PWD/ourMD5.cpp \
    $$PWD/OutputFile.cpp \
    $$PWD/QCELPAudioRTPSource.cpp \
    $$PWD/QuickTimeFileSink.cpp \
    $$PWD/RTPSink.cpp \
    $$PWD/RTPSource.cpp \
    $$PWD/RTSPRegisterSender.cpp \
    $$PWD/RTSPServerRegister.cpp \
    $$PWD/SimpleRTPSink.cpp \
    $$PWD/SIPClient.cpp \
    $$PWD/StreamParser.cpp \
    $$PWD/TheoraVideoRTPSink.cpp \
    $$PWD/TheoraVideoRTPSource.cpp \
    $$PWD/uLawAudioFilter.cpp \
    $$PWD/VP9VideoRTPSource.cpp \
    $$PWD/WAVAudioFileServerMediaSubsession.cpp \
    $$PWD/AACAudioStreamFramer.cpp \
    $$PWD/AC3AudioFileServerMediaSubsession.cpp \
    $$PWD/AC3AudioRTPSink.cpp \
    $$PWD/AC3AudioRTPSource.cpp \
    $$PWD/ADTSAudioFileServerMediaSubsession.cpp \
    $$PWD/ADTSAudioFileSource.cpp \
    $$PWD/AMRAudioFileServerMediaSubsession.cpp \
    $$PWD/AMRAudioFileSink.cpp \
    $$PWD/AMRAudioRTPSource.cpp \
    $$PWD/AMRAudioSource.cpp \
    $$PWD/AudioRTPSink.cpp \
    $$PWD/AVIDemuxedElementaryStream.cpp \
    $$PWD/AVIVideoDiscreteFramer.cpp \
    $$PWD/BasicUDPSink.cpp \
    $$PWD/BasicUDPSource.cpp \
    $$PWD/BitVector.cpp \
    $$PWD/ByteStreamFileSource.cpp \
    $$PWD/ByteStreamMultiFileSource.cpp \
    $$PWD/DeviceSource.cpp \
    $$PWD/DigestAuthentication.cpp \
    $$PWD/DVVideoRTPSource.cpp \
    $$PWD/DVVideoStreamFramer.cpp \
    $$PWD/EBMLNumber.cpp \
    $$PWD/FileSink.cpp \
    $$PWD/FramedFileSource.cpp \
    $$PWD/FramedFilter.cpp \
    $$PWD/FramedSource.cpp \
    $$PWD/H261VideoRTPSource.cpp \
    $$PWD/H263plusVideoFileServerMediaSubsession.cpp \
    $$PWD/H263plusVideoRTPSink.cpp \
    $$PWD/H263plusVideoRTPSource.cpp \
    $$PWD/H263plusVideoStreamFramer.cpp \
    $$PWD/H264or5VideoRTPSink.cpp \
    $$PWD/H264or5VideoStreamFramer.cpp \
    $$PWD/H264VideoFileServerMediaSubsession.cpp \
    $$PWD/H264VideoFileSink.cpp \
    $$PWD/H264VideoRTPSource.cpp \
    $$PWD/H264VideoStreamFramer.cpp \
    $$PWD/H265VideoFileServerMediaSubsession.cpp \
    $$PWD/H265VideoFileSink.cpp \
    $$PWD/H265VideoRTPSource.cpp \
    $$PWD/JPEGVideoRTPSink.cpp \
    $$PWD/JPEGVideoRTPSource.cpp \
    $$PWD/JPEGVideoSource.cpp \
    $$PWD/MatroskaDemuxedTrack.cpp \
    $$PWD/MatroskaFile.cpp \
    $$PWD/MatroskaFileParser.cpp \
    $$PWD/MatroskaFileServerDemux.cpp \
    $$PWD/MatroskaFileServerMediaSubsession.cpp \
    $$PWD/Media.cpp \
    $$PWD/MediaSource.cpp \
    $$PWD/MP3ADU.cpp \
    $$PWD/MP3ADURTPSink.cpp \
    $$PWD/MP3ADURTPSource.cpp \
    $$PWD/MP3AudioMatroskaFileServerMediaSubsession.cpp \
    $$PWD/MP3FileSource.cpp \
    $$PWD/MP3Internals.cpp \
    $$PWD/MP3StreamState.cpp \
    $$PWD/MP3Transcoder.cpp \
    $$PWD/MPEG1or2AudioStreamFramer.cpp \
    $$PWD/MPEG1or2DemuxedServerMediaSubsession.cpp \
    $$PWD/MPEG1or2VideoRTPSink.cpp \
    $$PWD/MPEG1or2VideoStreamFramer.cpp \
    $$PWD/MPEG2IndexFromTransportStream.cpp \
    $$PWD/MPEG2TransportStreamFromESSource.cpp \
    $$PWD/MPEG2TransportStreamFromPESSource.cpp \
    $$PWD/MPEG2TransportStreamTrickModeFilter.cpp \
    $$PWD/MPEG2TransportUDPServerMediaSubsession.cpp \
    $$PWD/MPEG4ESVideoRTPSink.cpp \
    $$PWD/MPEG4ESVideoRTPSource.cpp \
    $$PWD/MPEG4GenericRTPSink.cpp \
    $$PWD/MPEG4VideoFileServerMediaSubsession.cpp \
    $$PWD/MPEG4VideoStreamDiscreteFramer.cpp \
    $$PWD/MPEGVideoStreamFramer.cpp \
    $$PWD/MultiFramedRTPSource.cpp \
    $$PWD/OggDemuxedTrack.cpp \
    $$PWD/OggFile.cpp \
    $$PWD/OggFileParser.cpp \
    $$PWD/OggFileSink.cpp \
    $$PWD/PassiveServerMediaSubsession.cpp \
    $$PWD/ProxyServerMediaSession.cpp \
    $$PWD/QuickTimeGenericRTPSource.cpp \
    $$PWD/RTCP.cpp \
    $$PWD/RTPInterface.cpp \
    $$PWD/RTSPServerSupportingHTTPStreaming.cpp \
    $$PWD/SimpleRTPSource.cpp \
    $$PWD/StreamReplicator.cpp \
    $$PWD/T140TextRTPSink.cpp \
    $$PWD/TCPStreamSink.cpp \
    $$PWD/TextRTPSink.cpp \
    $$PWD/VideoRTPSink.cpp \
    $$PWD/VorbisAudioRTPSink.cpp \
    $$PWD/VorbisAudioRTPSource.cpp \
    $$PWD/VP8VideoRTPSink.cpp \
    $$PWD/VP8VideoRTPSource.cpp \
    $$PWD/VP9VideoRTPSink.cpp \
    $$PWD/WAVAudioFileSource.cpp \
    $$PWD/rtcp_from_spec.c
